version: 0.2

phases:
    install:
        commands:
        - echo Nothing to do here
        
    build:
        commands:
        - echo build started on 'date'
        - mvn install
    
artifacts:
    files:
        - target/messageUtil-1.0.jar